[package]
name = "orx-meta-queue"
version = "1.0.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "TODO"
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-meta-queue/"
keywords = ["queue", "meta", "metaprogramming", "type", "recursive"]
categories = ["data-structures", "rust-patterns", "no-std"]

[dependencies]
